server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/woc?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: true
logging:
  level:
    com.example.demo.mapper: debug
